stages:
  - prepare
  - build
  - package
  - upload
  - release

variables:
  FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"
  PUBLIC_BASE_URL: https://nightly.mtasa.hu/luajit
  OUTPUT_DIR: Bin/server
  BUILD_OVERRIDES: Shared/build_overrides.h
  NUM_CORES: 16

include:
  - local: .steps.gitlab-ci.yml
    inputs:
      platform: x86
  - local: .steps.gitlab-ci.yml
    inputs:
      platform: x64
#  - local: .steps.gitlab-ci.yml
#    inputs:
#      platform: arm
#  - local: .steps.gitlab-ci.yml
#    inputs:
#      platform: arm64

release:
  stage: release
  image: ${CI_REGISTRY}/oaklab/ci-tools:stable
  needs:
    - upload [x86]
    - upload [x64]
#    - upload [arm]
#    - upload [arm64]
  variables:
    GIT_STRATEGY: none
  before_script:
    - eval "$(setup-glab)"
  script:
    - RELEASE_TAG="${NET_VERSION}-r${NET_REVISION}"
    - ASSETS="[$(cat assets/* | sed '/^$/d' | tr '\n' ',' | sed 's/,$//')]"
    - glab release delete "${RELEASE_TAG}" --with-tag --yes || true
    - glab release create "${RELEASE_TAG}" --name "${RELEASE_TAG}" --assets-links "${ASSETS}"
  tags:
    - platform:any
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
