stages:
  - prepare
  - build
  - package
  - upload
  - release
  - index

variables:
  FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"
  PUBLIC_BASE_URL: https://nightly.mtasa.hu/luajit
  OUTPUT_DIR: Bin/server
  BUILD_OVERRIDES: Shared/build_overrides.h
  NUM_CORES: 16

include:
  - local: .steps.gitlab-ci.yml
    inputs:
      platform: x86
  - local: .steps.gitlab-ci.yml
    inputs:
      platform: x64
#  - local: .steps.gitlab-ci.yml
#    inputs:
#      platform: arm
#  - local: .steps.gitlab-ci.yml
#    inputs:
#      platform: arm64

release:
  stage: release
  image: ${CI_REGISTRY}/oaklab/ci-tools:stable
  needs:
    - prepare [x86]
    - upload [x86]
    - upload [x64]
#    - upload [arm]
#    - upload [arm64]
  variables:
    GIT_STRATEGY: none
  before_script:
    - eval "$(setup-glab)"
  script:
    - RELEASE_TAG="${NET_VERSION}-r${NET_REVISION}"
    - ASSETS="[$(cat assets/* | sed '/^$/d' | tr '\n' ',' | sed 's/,$//')]"
    - >-
      glab release delete "${RELEASE_TAG}"
      --repo "${CI_PROJECT_PATH}"
      --with-tag --yes
      || true
    - >-
      glab release create "${RELEASE_TAG}"
      --repo "${CI_PROJECT_PATH}"
      --ref "${CI_COMMIT_SHA}"
      --name "${RELEASE_TAG}"
      --assets-links "${ASSETS}"
  tags:
    - platform:any
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

generate index:
  stage: index
  image:
    name: ${CI_REGISTRY}/crys/web-indexer:stable
    entrypoint: [""]
  needs:
    - release
  variables:
    TZ: Europe/Budapest
    GIT_STRATEGY: none
  script:
    - >-
      web-indexer
      --recursive
      --quiet
      --use-metadata-mtime
      --sort-by last_modified
      --order desc
      "s3://${S3_BUCKET}/"
      "s3://${S3_BUCKET}/"
  tags:
    - platform:any
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
