stages:
  - prepare
  - build
  - package
  - upload
  - release

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/mtasa-blue"
  PACKAGE_DIR: "${CI_PROJECT_DIR}/packages"
  OUTPUT_DIR: Bin/server
  BUILD_OVERRIDES: Shared/build_overrides.h

include:
  - local: .steps.gitlab-ci.yml
    inputs:
      arch: x64
      image: latest
  - local: .steps.gitlab-ci.yml
    inputs:
      arch: arm64
      image: arm64

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  dependencies:
    - prepare [x64]
    - package [x64]
    - package [arm64]
  variables:
    GIT_STRATEGY: none
  script:
    - cd "${PACKAGE_DIR}"
    - |
      set --
      for package in *; do
        set -- "$@" --assets-link "{\"name\":\"${package}\",\"direct_asset_path\":\"/${package/-*}.tar.${package##*.}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${NET_VERSION}-r${NET_REVISION}-${CI_PIPELINE_IID}/${package}\",\"link_type\":\"package\"}"
      done
    - >-
      release-cli create
      --name "v${NET_VERSION}-r${NET_REVISION}-${CI_PIPELINE_IID}"
      --tag-name "v${NET_VERSION}-r${NET_REVISION}-${CI_PIPELINE_IID}"
      "$@"
  rules:
    - if: $CI_COMMIT_BRANCH
