stages:
  - prepare
  - build
  - package
  - upload
  - release

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/mtasa-blue"
  PACKAGE_DIR: "${CI_PROJECT_DIR}/packages"
  OUTPUT_DIR: Bin/server
  BUILD_OVERRIDES: Shared/build_overrides.h

include:
  - local: .steps.gitlab-ci.yml
    inputs:
      arch: x64
      image: latest
