spec:
  inputs:
    platform:
      type: string
      options:
        - x86
        - x64
#        - arm
#        - arm64
---
prepare [$[[ inputs.platform ]]]:
  stage: prepare
  image: ${CI_REGISTRY}/oaklab/ci-tools:stable
  artifacts:
    paths:
      - $OUTPUT_DIR
    reports:
      dotenv: .env
  variables:
    #LATEST_URL_TEMPLATE: https://nightly.multitheftauto.com/?multitheftauto_linuxNIGHTLY_SUFFIX-1.6-rc-latest
    LATEST_URL_TEMPLATE: https://nightly.multitheftauto.com/multitheftauto_linuxNIGHTLY_SUFFIX-1.6.0-rc-24124.tar.gz
    GIT_STRATEGY: none
  before_script:
    - |-
      if [ "$[[ inputs.platform ]]" != "x86" ]; then
        NIGHTLY_SUFFIX="_$[[ inputs.platform ]]"
      else
        NIGHTLY_SUFFIX=""
      fi
      LATEST_URL=${LATEST_URL_TEMPLATE/NIGHTLY_SUFFIX/$NIGHTLY_SUFFIX}
      ci-logf info 'Computed URL: %s' "$LATEST_URL"
  script:
    - |-
      set -e
      wget --quiet --content-disposition "$LATEST_URL"
      FILENAME=$(ls multitheftauto_linux* | head -n 1)
      test -f "${FILENAME}"
      tar xvaf "${FILENAME}" --strip-components=1 --one-top-level="${OUTPUT_DIR}" --wildcards "*/net.so"
      VER=${FILENAME#*-}
      VER=${VER/-*}
      REV=${FILENAME#*-full_rc-}
      REV=${REV#*-rc-}
      REV=${REV%-*}
      REV=${REV%%.*}
      PREFIX=${FILENAME%%-*}
      echo "PACKAGE=${PREFIX}-${VER}-luajit-${REV}" >> .env
      echo "NET_VERSION=$VER" >> .env
      echo "NET_REVISION=$REV" >> .env
      ci-log info Prepared environment
      ci-logf info " - %s\n" $(cat .env)
  tags:
    - platform:any
  rules:
    - if: $CI_COMMIT_BRANCH

build [$[[ inputs.platform ]]]:
  stage: build
  image:
    name: ${CI_REGISTRY_IMAGE}/build:multiarch
    entrypoint: [""]
  needs:
    - prepare [$[[ inputs.platform ]]]
  artifacts:
    paths:
      - $OUTPUT_DIR
  before_script:
    - |
      cat > "Shared/build_overrides.h" <<EOF
      #undef MTASA_VERSION_TYPE
      #undef MTASA_VERSION_BUILD
      #define MTASA_VERSION_TYPE VERSION_TYPE_RELEASE
      #define MTASA_VERSION_BUILD $NET_REVISION
      EOF
  script:
    - ./linux-build.sh --arch="$[[ inputs.platform ]]"
    - cp Server/output/* "$OUTPUT_DIR"
  tags:
    - platform:linux/amd64
  rules:
    - if: $CI_COMMIT_BRANCH

package [$[[ inputs.platform ]]]:
  stage: package
  image: ${CI_REGISTRY}/oaklab/ci-tools:stable
  needs:
    - prepare [$[[ inputs.platform ]]]
    - build [$[[ inputs.platform ]]]
  artifacts:
    paths:
      - packages
    reports:
      dotenv: .env
  variables:
    GIT_STRATEGY: none
  script:
    - echo "NET_VERSION=$NET_VERSION" >> .env
    - echo "NET_REVISION=$NET_REVISION" >> .env
    - cd "$OUTPUT_DIR"
    - find . -type f -name "*.so" -exec chmod -x "{}" \;
    - mkdir -p mods/deathmatch
    - cd "$CI_PROJECT_DIR"
    - mv "$OUTPUT_DIR" "${PACKAGE}"
    - mkdir -p packages
    - tar --owner=0 --group=0 -cvaf "packages/${PACKAGE}.tar.xz" "${PACKAGE}"
  tags:
    - platform:any
  rules:
    - if: $CI_COMMIT_BRANCH

upload [$[[ inputs.platform ]]]:
  stage: upload
  image: ${CI_REGISTRY}/oaklab/ci-tools:stable
  needs:
    - package [$[[ inputs.platform ]]]
  variables:
    GIT_STRATEGY: none
  artifacts:
    paths:
      - assets
    reports:
      dotenv: .env
  before_script:
    - eval "$(setup-rclone)"
  script:
    - mkdir -p assets
    - >-
      rclone copy
      --stats-log-level NOTICE --stats 9999h
      packages/ "s3:$S3_BUCKET/luajit/"
    - cd packages
    - |
      for package in *; do
        package_url="${PUBLIC_BASE_URL}/${package}"
        echo "{\"name\":\"${package}\",\"direct_asset_path\":\"/${package}\",\"url\":\"${package_url}\",\"link_type\":\"package\"}" > "${CI_PROJECT_DIR}/assets/${package}.json"
      done
  tags:
    - platform:any
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
